import './globals.css';
import { Inter } from 'next/font/google';
import React, { ReactNode } from 'react'; // Import React and ReactNode for type annotations

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Define the props type for the RootLayout component
interface RootLayoutProps {
  children: ReactNode; // Type for children prop
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
